apiVersion: idp.rottler.io/v1alpha1
kind: ApplicationEnvironment
metadata:
  name: ${{ values.teamName }}-${{ values.system }}-${{ values.slug }}
  annotations:
    # Ensure ApplicationEnvironment is deleted before ArgoCD project
    argocd.argoproj.io/sync-wave: "1"
  labels:
    idp.rottler.io/team: ${{ values.teamName }}
    idp.rottler.io/system: ${{ values.system }}
    idp.rottler.io/component: ${{ values.slug }}
spec:
  team: ${{ values.teamName }}
  system: ${{ values.system }}
  component: ${{ values.slug }}
