apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentId }}
  title: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    # GitLab project path. Used by the GitLab plugin for MRs, pipelines, etc.
    gitlab.com/project-slug: idp/${{ values.teamName }}/${{ values.componentId }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
